version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    env_file:
      - ./.env
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  nodejs:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    links: 
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$PORT
    